### PR TITLE
Rebase on upstream Termux

### PR DESCRIPTION
**Pull request by zhaofengli**
I manually applied the Nix-on-Droid-specific bits on top of the upstream Termux app. The diff here is too large - See [the diff against upstream Termux](https://github.com/termux/termux-app/compare/master...zhaofengli:nix-on-droid-app:big-rebase). I took some creative liberties and tried to keep the diff as minimal as possible.

Unfortunately, merging the addons (no longer paid since the Play Store version got discontinued) seems be a messy task.

The app seems kind of usable, with new features like shortcuts (no more separate launcher icon for the failsafe mode). Launching multiple sessions seem to work as well:

<details>

Screenshot_20220913-014602_One UI Home
</details>

Ref: https://github.com/t184256/nix-on-droid/issues/168#issuecomment-1025217178

### CODE REVIEW

**Comment by t184256** [comment]
Just a heads-up to avoid being impolite: I've noticed this merge request and I do plan to wrestle Android's horrible buildsystems, build and test it, but it'll take time.

We should figure out what do we lose as we move away from bundling addons; e.g., does the very functionality of styling go away or just the UI for it and we can compensate by writing a Nix module?

From a cursory glance, the README prefixing seems missing, but I haven't reviewed the code in details yet.

And, of course, thanks for stepping up and doing the thing I try to avoid.

**Comment by t184256** [comment]
Managed to build it successfully, bootstrap works. Styling from the menu no longer works, prompting to install a plugin (since that won't work for us, maybe that text should be replaced).

Dropping a font/colorscheme into `~/.termux` changes the font/colorscheme, so we can probably get away with a module as a replacement.

Another formerly integrated plugin is Widget we're now dropping, and I doubt it has been functional before.

Will continue reviewing later during the week.

**Comment by t184256** [comment]
Observations so far:
* Styling menu: IMO configuring with a module is enough of a workaround, would be good to change the text.
* There are new configurable options in recent termux config files; we should expose them too.
* There was a weird regression for me with keyboard overlapping the terminal, but playing with new in-app settings seems to have changed that.
* Recovery no longer works and instead executes a normal session, that should be investigated and fixed.

**Comment by zhaofengli** [comment]
> * 
> 
> * Recovery no longer works and instead executes a normal session, that should be investigated and fixed.

I forgot to change the package name in the extra flag of the intent to match `EXTRA_FAILSAFE_SESSION`. The failsafe session works for me now.

**Comment by t184256** [comment]
Can confirm, failsafe works for me now, even better than it used to (when it's not the first session).

Another thing I've found is the version name has not been deviated from upstream. I suggest
```
        versionCode 118030
        versionName "0.118.0_v0.3.0_nix"
```
and either relaxing or dropping the semver check.

**Comment by zhaofengli** [comment]
Ok, added our downstream version by reassigning `versionCode` further down. This way we can easily merge upstream periodically without causing merge conflicts.

**Comment by t184256** [comment]
Thanks a lot for taking the time to do this!

I've been running it for a while with no adverse effects spotted and so I've merged it manually in time for 22.11 release. (v0.118.0_v0.3.0_nix) with minimal modifications. Hope F-Droid does its thing smoothly and we'll see it there someday next week....

**Pull request closed without merging**
